export const hotelAmenities = {
  // Видео/аудио
  tv: { icon: 'lucide:tv', title: 'Телевизор' },
  two_tv: { icon: 'lucide:tv-2', title: 'Два телевизора' },
  satellite_television: {
    icon: 'lucide:satellite',
    title: 'Спутниковое телевидение',
  },
  cable_television: { icon: 'lucide:cable', title: 'Кабельное телевидение' },
  interactive_web_tv: {
    icon: 'lucide:monitor-play',
    title: 'Интерактивное телевидение',
  },
  dvd_player: { icon: 'lucide:disc', title: 'DVD-плеер' },
  movies: { icon: 'lucide:film', title: 'Подборка видео/аудио' },
  home_cinema: { icon: 'lucide:projector', title: 'Домашний кинотеатр' },
  karaoke: { icon: 'lucide:mic', title: 'Караоке' },
  media_center: { icon: 'lucide:music', title: 'Музыкальный центр' },
  chinese_channel: { icon: 'lucide:languages', title: 'Китайский канал' },
  digital_tv: { icon: 'lucide:monitor', title: 'Цифровое тв' },
  flat_screen_TV: {
    icon: 'lucide:monitor',
    title: 'Телевизор с плоским экраном',
  },
  hbo: { icon: 'lucide:play-circle', title: 'HBO' },
  android_tv: { icon: 'lucide:smartphone', title: 'Android TV' },
  audio_stereo_system: {
    icon: 'lucide:volume-2',
    title: 'Аудио стереосистема',
  },
  netflix_premium: { icon: 'mdi:netflix', title: 'Netflix Premium' },

  // Интернет/телефония
  wifi_internet: {
    icon: 'material-symbols:wifi-rounded',
    title: 'Wi-Fi интернет',
  },
  wifi: { icon: 'material-symbols:wifi-rounded', title: 'Wi-Fi интернет' },
  internet: { icon: 'lucide:globe', title: 'Интернет' },
  telephone: { icon: 'lucide:phone', title: 'Телефон' },
  ip_telephone: { icon: 'lucide:phone-call', title: 'IP-телефон' },
  two_line_phone: { icon: 'tabler:phone-plus', title: 'Две телефонные линии' },
  '121': { icon: 'lucide:router', title: 'Роутер' },
  in_room_telephone: {
    icon: 'lucide:phone-incoming',
    title: 'Внутренний телефон',
  },

  // Размещение с питомцами
  '789': { icon: 'mdi:water-boiler', title: 'Поилка' },
  possible_with_pets: { icon: 'lucide:heart', title: 'Можно с питомцами' },
  without_pets: { icon: 'lucide:x-circle', title: 'Без питомцев' },
  pet_toys: { icon: 'mdi:tennis-ball', title: 'Игрушки для питомцев' },
  pet_food: { icon: 'mdi:food-dog-bowl', title: 'Корм' },
  pet_bed: { icon: 'mdi:bed-outline', title: 'Лежанка' },
  pet_tray: { icon: 'mdi:pot', title: 'Лоток' },
  pet_bag: { icon: 'lucide:shopping-bag', title: 'Пакетик для выгула' },
  pet_diaper: { icon: 'mdi:diaper', title: 'Пеленка' },
  pet_bowl: { icon: 'mdi:bowl-mix', title: 'Миска' },

  // Внешняя территория и вид из окон
  magical_ambience: { icon: 'lucide:sparkles', title: 'Волшебная атмосфера' },
  view_to_stadium: { icon: 'mdi:stadium-variant', title: 'Вид на стадион' },
  window_leaf: { icon: 'mdi:window-open-variant', title: 'Форточка' },
  city_view: { icon: 'lucide:buildings', title: 'Вид на город' },
  floor_to_ceiling_windows: {
    icon: 'mdi:window-maximize',
    title: 'Панорамные окна',
  },
  balcony: { icon: 'mdi:balcony', title: 'Балкон' },
  balcony_with_view: { icon: 'mdi:balcony', title: 'Балкон с красивым видом' },
  balcony_with_deck_chairs: {
    icon: 'mdi:chair-rolling',
    title: 'Балкон с шезлонгом',
  },
  loggia: { icon: 'mdi:home-outline', title: 'Лоджия' },
  terrace: { icon: 'mdi:deck', title: 'Терраса' },
  window_to_hotel_atrium: {
    icon: 'mdi:home-city-outline',
    title: 'Окна в атриум отеля',
  },
  lake_view: { icon: 'mdi:lake', title: 'Вид на озеро' },
  mountain_view: { icon: 'lucide:mountain', title: 'Вид на горы' },
  private_room_entrance: { icon: 'lucide:door-open', title: 'Отдельный вход' },
  court_view: { icon: 'mdi:home-group', title: 'Вид во двор' },
  view_race_track: { icon: 'mdi:horse-variant', title: 'Вид на ипподром' },
  garden_view: { icon: 'lucide:flower-2', title: 'Вид на сад' },
  park_view: { icon: 'lucide:trees', title: 'Вид на парк' },
  river_view: { icon: 'mdi:river', title: 'Вид на реку' },
  sea_view: { icon: 'lucide:waves', title: 'Вид на море' },
  obstructed_view: { icon: 'lucide:eye-off', title: 'Без вида' },
  heritage_view: {
    icon: 'lucide:landmark',
    title: 'Вид на достопримечательность',
  },
  yacht_marine_view: { icon: 'mdi:yacht', title: 'Вид на марину' },
  cathedral_view: { icon: 'mdi:church', title: 'Вид на собор' },
  outdoor_shower: { icon: 'mdi:shower', title: 'Душ у бассейна' },
  open_air_bath: { icon: 'mdi:hot-tub', title: 'Купель' },

  // Мебель
  nightstands: { icon: 'mdi:table-furniture', title: 'Тумбы' },
  chairs: { icon: 'lucide:armchair', title: 'Стулья' },
  closet_for_clothes: { icon: 'mdi:wardrobe', title: 'Шкаф для одежды' },
  wardrobe: { icon: 'mdi:wardrobe-outline', title: 'Гардеробная' },
  hangers: { icon: 'mdi:hanger', title: 'Вешалки' },
  journal_table: { icon: 'mdi:table-furniture', title: 'Журнальный столик' },
  desk: { icon: 'lucide:laptop', title: 'Письменный стол' },
  conference_table: { icon: 'mdi:table-large', title: 'Стол для переговоров' },
  dinner_table: { icon: 'mdi:table-chair', title: 'Обеденный стол' },
  luggage_stand: { icon: 'mdi:bag-suitcase', title: 'Багажная тумба' },
  bar: { icon: 'mdi:glass-cocktail', title: 'Барная стойка' },
  mirror: { icon: 'lucide:mirror', title: 'Зеркало' },
  commode: { icon: 'mdi:dresser', title: 'Комод' },
  padded_stools: { icon: 'mdi:chair-rolling', title: 'Пуфики' },
  carpet: { icon: 'mdi:rug', title: 'Ковер' },
  exclusive_furniture: { icon: 'mdi:star', title: 'Эксклюзивная мебель' },
  'furniture set': { icon: 'mdi:sofa', title: 'Мебельный гарнитур' },
  soft_furniture: { icon: 'mdi:sofa-single', title: 'Мягкая мебель' },
  table: { icon: 'lucide:table', title: 'Стол' },
  sofa_bed: { icon: 'mdi:sofa', title: 'Диван' },
  armchairs: { icon: 'lucide:armchair', title: 'Кресла' },
  toilet_table: { icon: 'mdi:mirror', title: 'Туалетный столик' },
  sliding_door_wardrobe: { icon: 'mdi:wardrobe', title: 'Шкаф-купе' },
  armchair: { icon: 'lucide:armchair', title: 'Кресло' },
  studio_couch: { icon: 'mdi:bed-single', title: 'Диван-кровать' },
  folding_sofa: { icon: 'mdi:sofa', title: 'Раскладной диван' },
  folding_armchair: { icon: 'mdi:chair-rolling', title: 'Раскладное кресло' },
  chair: { icon: 'lucide:chair', title: 'Стул' },
  nightstand: { icon: 'mdi:table-furniture', title: 'Тумба' },
  non_folding_sofa: { icon: 'mdi:sofa', title: 'Нераскладной диван' },
  outdoor_furniture: { icon: 'mdi:patio-heater', title: 'Уличная мебель' },
  massage_chair: { icon: 'mdi:spa', title: 'Массажное кресло' },

  // Прочее
  maid_service: { icon: 'mdi:room-service', title: 'Обслуживание номеров' },
  washer_dryer: {
    icon: 'mdi:washing-machine',
    title: 'Стиральная машина и сушилка',
  },
  three_rooms: { icon: 'mdi:home-variant', title: 'Три комнаты' },
  toaster: { icon: 'mdi:toaster-oven', title: 'Тостер' },
  barbecue_facilities: {
    icon: 'mdi:grill',
    title: 'Принадлежности для барбекю',
  },
  cabinet: { icon: 'mdi:file-cabinet', title: 'Кабинет' },
  carpet_covering: { icon: 'mdi:rug', title: 'Ковровое покрытие' },
  central_air_conditioning: {
    icon: 'mdi:air-conditioner',
    title: 'Центральное кондиционирование',
  },
  clothes_airer: { icon: 'mdi:hanger', title: 'Сушилка для белья' },
  coffee_end_tables: { icon: 'mdi:coffee-table', title: 'Кофейный столик' },
  cookware: { icon: 'mdi:pot-mix', title: 'Кухонная посуда' },
  cosmetic_mirror: { icon: 'mdi:mirror', title: 'Косметическое зеркало' },
  dinner_zone: { icon: 'mdi:table-chair', title: 'Обеденная зона' },
  dresser: { icon: 'mdi:dresser', title: 'Туалетный столик' },
  drinking_water: { icon: 'mdi:cup-water', title: 'Питьевая вода' },
  flatware: { icon: 'mdi:silverware-fork-knife', title: 'Столовые приборы' },
  '1': { icon: 'lucide:help-circle', title: 'Дополнительная услуга' },
  two_rooms: { icon: 'mdi:home-outline', title: 'Две комнаты' },
  kitchen: { icon: 'lucide:chef-hat', title: 'Кухня' },
  soundproofed_room: {
    icon: 'mdi:volume-off',
    title: 'Звуконепроницаемые стены и окна',
  },
  minibar: { icon: 'mdi:fridge', title: 'Мини-бар' },
  fireplace: { icon: 'mdi:fireplace', title: 'Камин' },
  writing_utensils: { icon: 'lucide:pen', title: 'Письменные принадлежности' },
  daily_press: { icon: 'mdi:newspaper', title: 'Свежая пресса' },
  tea_set: { icon: 'mdi:tea', title: 'Чайный набор' },
  set_of_dishes: { icon: 'mdi:bowl-mix-outline', title: 'Набор посуды' },
  information_card: {
    icon: 'mdi:information',
    title: 'Информационная карта, меню',
  },
  safe: { icon: 'mdi:safe', title: 'Сейф' },
  mineral_water: { icon: 'mdi:bottle-water', title: 'Минеральная вода' },
  dishwasher: { icon: 'mdi:dishwasher', title: 'Посудомоечная машина' },
  trouser_press: { icon: 'mdi:iron', title: 'Пресс для глажения брюк' },
  washing_machine: { icon: 'mdi:washing-machine', title: 'Стиральная машина' },
  kettle: { icon: 'mdi:kettle-steam', title: 'Чайник' },
  three_bedrooms: { icon: 'mdi:bed-double', title: 'Три спальни' },
  ironing_board: { icon: 'mdi:iron', title: 'Гладильная доска' },
  tile_covering: { icon: 'mdi:texture', title: 'Плиточное покрытие' },
  cork_flooring: { icon: 'mdi:texture', title: 'Пробковый пол' },
  two_bedrooms: { icon: 'mdi:bed-double-outline', title: 'Две спальни' },
  hardwood_floors: { icon: 'mdi:texture', title: 'Паркет' },
  pillows_menu: { icon: 'mdi:pillow', title: 'Меню подушек' },
  mini_kitchen: { icon: 'mdi:stove', title: 'Мини-кухня' },
  kitchenette: { icon: 'mdi:fridge-outline', title: 'Кухонный уголок' },
  window_screen: { icon: 'mdi:window-open', title: 'Москитная сетка' },
  four_rooms: { icon: 'mdi:home-city', title: 'Четыре комнаты' },
  garbage_disposal: { icon: 'mdi:delete', title: 'Уничтожитель мусора' },
  glasses: { icon: 'mdi:glass-mug', title: 'Стаканы и чашки' },
  high_ceilings: { icon: 'mdi:arrow-up-bold', title: 'Высокие потолки' },
  kitchen_utensils: { icon: 'mdi:silverware-spoon', title: 'Кухонная утварь' },
  laminate: { icon: 'mdi:texture', title: 'Ламинат' },
  living_area: { icon: 'mdi:sofa', title: 'Гостиная зона' },
  outdoor_grill: { icon: 'mdi:grill-outline', title: 'Мангал' },
  non_smoking_room: { icon: 'mdi:smoking-off', title: 'Номер для некурящих' },
  pool: { icon: 'mdi:pool', title: 'Открытый бассейн' },
  premium_beauty_products: {
    icon: 'mdi:spa',
    title: 'Косметические принадлежности премиум-класса',
  },
  swimming_pool: { icon: 'mdi:pool', title: 'Бассейн' },
  bathhouse: { icon: 'mdi:hot-tub', title: 'Баня' },
  mosquito_net: {
    icon: 'mdi:bug-outline',
    title: 'Москитная сетка над кроватью',
  },

  // Кровати
  '126': { icon: 'mdi:bed-single-outline', title: 'Раскладушка' },
  two_queen_size_beds: {
    icon: 'mdi:bed-queen',
    title: 'Две кровати Queen size',
  },
  two_king_size_beds: { icon: 'mdi:bed-king', title: 'Две кровати King size' },
  five_single_beds: {
    icon: 'mdi:bed-single',
    title: 'Пять односпальных кроватей',
  },
  four_beds: { icon: 'mdi:bed-double', title: 'Четыре односпальные кровати' },
  tablen2: { icon: 'mdi:bed-outline', title: 'Тейбл' },
  six_beds: { icon: 'mdi:bed-double', title: 'Шесть односпальных кроватей' },
  three_double_beds: { icon: 'mdi:bed-king', title: 'Три двуспальные кровати' },
  king_bed: { icon: 'mdi:bed-king-outline', title: 'Кровать King size' },
  queen_bed: { icon: 'mdi:bed-queen-outline', title: 'Кровать Queen size' },
  double_bed: { icon: 'mdi:bed-double-outline', title: 'Двуспальная кровать' },
  two_double_beds: { icon: 'mdi:bed-double', title: 'Две двуспальные кровати' },
  full_bed: { icon: 'mdi:bed-outline', title: 'Полутороспальная кровать' },
  two_full_beds: {
    icon: 'mdi:bed-double-outline',
    title: 'Две полутороспальные кровати',
  },
  single_bed: { icon: 'mdi:bed-single-outline', title: 'Односпальная кровать' },
  two_single_beds: {
    icon: 'mdi:bed-single',
    title: 'Две односпальные кровати',
  },
  two_single_or_big_double_bed: {
    icon: 'mdi:bed-double',
    title: 'Две односпальные или большая двуспальная',
  },
  hypoallergenic_linen: { icon: 'mdi:leaf', title: 'Гипоаллергенное белье' },
  orthopedic_mattress: {
    icon: 'mdi:medical-bag',
    title: 'Ортопедический матрас',
  },
  child_rollaway: { icon: 'mdi:baby', title: 'Детская кровать' },
  bunk_beds: { icon: 'mdi:bunk-bed', title: 'Двухъярусные кровати' },
  krovatka: { icon: 'mdi:baby-carriage', title: 'Кроватка' },
  three_single_beds: {
    icon: 'mdi:bed-single',
    title: 'Три односпальные кровати',
  },
  three_full_beds: {
    icon: 'mdi:bed-double',
    title: 'Три полутороспальные кровати',
  },
  mezzanine_bed: { icon: 'mdi:bunk-bed-outline', title: 'Кровать-антресоль' },
  folding_single_bed: {
    icon: 'mdi:bed-single-outline',
    title: 'Раскладная одноместная кровать',
  },
  two_bunk_beds: { icon: 'mdi:bunk-bed', title: 'Две двухъярусные кровати' },
  transformer_bed: {
    icon: 'mdi:swap-horizontal',
    title: 'Кровать-трансформер',
  },

  // Ванная комната
  separate_closet: { icon: 'mdi:door-closed', title: 'Раздельный санузел' },
  two_bathrooms: { icon: 'mdi:shower', title: 'Две ванные комнаты' },
  hygienic_shower: { icon: 'mdi:spray', title: 'Гигиенический душ' },
  three_bathrooms: { icon: 'mdi:shower', title: 'Три ванные комнаты' },
  toilet: { icon: 'mdi:toilet', title: 'Туалет' },
  additional_bathroom: {
    icon: 'mdi:shower',
    title: 'Дополнительная ванная комната',
  },
  water_heater: { icon: 'mdi:water-boiler', title: 'Водонагреватель' },
  warm_floor: { icon: 'mdi:radiator', title: 'Теплый пол' },
  bathroom_amenities: {
    icon: 'mdi:bottle-soda',
    title: 'Банные принадлежности',
  },
  bathrobe: { icon: 'mdi:human', title: 'Халаты' },
  bath_towels: { icon: 'mdi:hanger', title: 'Банные полотенца' },
  beach_towels: { icon: 'mdi:beach', title: 'Пляжные полотенца' },
  slippers: { icon: 'mdi:shoe-sneaker', title: 'Тапочки' },
  hygienic_aids: { icon: 'mdi:toothbrush', title: 'Гигиенические средства' },
  beauty_aids: {
    icon: 'mdi:face-woman-outline',
    title: 'Косметические средства',
  },
  sauna: { icon: 'mdi:hot-tub', title: 'Сауна' },
  bathroom: { icon: 'mdi:shower', title: 'Ванная комната' },
  shower_cabin: { icon: 'mdi:shower', title: 'Душевая кабина' },
  bathtub: { icon: 'mdi:bathtub-outline', title: 'Ванна' },
  bath_or_shower: { icon: 'mdi:shower', title: 'Ванна или душевая кабина' },
  jacuzzi_bathroom: { icon: 'mdi:hot-tub', title: 'Ванная с джакузи' },
  aeromassage_bath: { icon: 'mdi:hot-tub', title: 'Аэромассажная ванна' },
  hydromassage_bath: { icon: 'mdi:spa-outline', title: 'Гидромассажная ванна' },
  hydromassage_shower: { icon: 'mdi:shower', title: 'Гидромассажный душ' },
  bathroom_with_wc: { icon: 'mdi:toilet', title: 'Санузел' },
  additional_bathroom_with_wc: {
    icon: 'mdi:toilet',
    title: 'Дополнительный санузел',
  },
  bidet: { icon: 'mdi:toilet', title: 'Биде' },
  sink: { icon: 'mdi:sink', title: 'Раковина' },
  toiletry: { icon: 'mdi:bottle-soda-outline', title: 'Туалетные средства' },
  bathroom_amenity_set: { icon: 'mdi:spa', title: 'Гостиничная парфюмерия' },
  shared_bathroom: { icon: 'mdi:account-group', title: 'Общая ванная комната' },
  toilet_bowl: { icon: 'mdi:toilet', title: 'Унитаз' },
  outside_bathroom: { icon: 'mdi:shower', title: 'Внешняя ванная комната' },
  shared_bathroom_and_toilet_on_floor: {
    icon: 'mdi:account-group',
    title: 'Санузел на этаже',
  },
  shower: { icon: 'mdi:shower', title: 'Душ' },
  rain_shower: { icon: 'mdi:weather-rainy', title: 'Тропический душ' },

  // Оборудование и электроника
  phone: { icon: 'lucide:phone', title: 'Телефон' },
  work_table: { icon: 'mdi:desk', title: 'Рабочий стол' },
  multi: { icon: 'mdi:pot-mix', title: 'Мультиварка' },
  kitchen_mitten: { icon: 'mdi:hand-back-right', title: 'Кухонная варежка' },
  veshalka: { icon: 'mdi:hanger', title: 'Напольная вешалка' },

  // Электроника
  cooler_on_the_floor: { icon: 'mdi:water-pump', title: 'Кулер на этаже' },
  smart_house: { icon: 'mdi:home-automation', title: 'Система умный дом' },
  electronic_locks: { icon: 'mdi:lock-smart', title: 'Электронные замки' },
  stove: { icon: 'mdi:stove', title: 'Плита для приготовления пищи' },
  coffee_machine: { icon: 'mdi:coffee-maker', title: 'Кофемашина' },
  split_air_conditioning_system: {
    icon: 'mdi:air-conditioner',
    title: 'Сплит-система',
  },
  refrigerator: { icon: 'mdi:fridge', title: 'Холодильник' },
  air_conditioning: { icon: 'mdi:air-conditioner', title: 'Кондиционер' },
  air_conditioning_individually_controlled_in_room: {
    icon: 'mdi:thermostat',
    title: 'Система климат-контроля',
  },
  lamp: { icon: 'lucide:lamp', title: 'Светильник' },
  desk_lamps: { icon: 'mdi:desk-lamp', title: 'Настольные лампы' },
  cooler: { icon: 'mdi:water-pump', title: 'Кулер' },
  hairdryer: { icon: 'mdi:hair-dryer', title: 'Фен' },
  fan: { icon: 'lucide:fan', title: 'Вентилятор' },
  scales: { icon: 'mdi:scale-bathroom', title: 'Электронные весы' },
  alarm_clock: { icon: 'lucide:alarm-clock', title: 'Будильник' },
  security_system: { icon: 'mdi:security', title: 'Система безопасности' },
  microwave: { icon: 'mdi:microwave', title: 'Микроволновая печь' },
  iron: { icon: 'mdi:iron', title: 'Утюг' },
  radio: { icon: 'lucide:radio', title: 'Радио' },
  heater: { icon: 'mdi:radiator', title: 'Обогреватель' },
  pc: { icon: 'lucide:pc', title: 'Персональный компьютер' },
  fax: { icon: 'mdi:fax', title: 'Факс' },
  heating: { icon: 'mdi:radiator', title: 'Отопление' },
  magnitofon: { icon: 'mdi:cassette', title: 'Магнитофон' },
  mini_fridge: { icon: 'mdi:fridge-outline', title: 'Мини-холодильник' },
  usb: { icon: 'mdi:usb-port', title: 'USB' },
  fan_coil: { icon: 'mdi:fan', title: 'Фанкойл' },
  drying_cabinet: { icon: 'mdi:wardrobe', title: 'Сушильный шкаф' },
  touch_panel_lighting: {
    icon: 'mdi:lightbulb-on',
    title: 'Сенсорные панели для управления освещением',
  },
  alarm_oclock: { icon: 'lucide:alarm-clock', title: 'Часы-будильник' },
  parking: { icon: 'streamline:parking-sign-solid', title: 'Парковка' },
  concierge_service: {
    icon: 'dashicons:admin-users',
    title: 'Консьерж-сервис',
  },
  restaurant: {
    icon: 'fluent-emoji-high-contrast:fork-and-knife-with-plate',
    title: 'Ресторан',
  },
}
